backend:
  name: git-gateway
  branch: master # CONFIRME novamente se sua branch principal no GitHub é "master" ou "main"

# Configurações OBRIGATÓRIAS para upload de imagens:
media_folder: "static/img/uploads" # Onde as imagens serão salvas no seu repositório
public_folder: "/img/uploads"      # Como essas imagens serão acessadas no site

# Configuração para formatar o JSON corretamente:
output:
  path: "data"
  pretty: true # Formata o JSON com indentação

collections:
  - name: "cardapio"
    label: "Cardápio"
    format: json
    files:
      - file: "data/cardapio.json"
        label: "Cardápio"
        name: "cardapio"
        fields:
          - label: "Pizzas Tradicionais"
            name: "tradicionais"
            widget: list
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Ingredientes", name: "ingredientes", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Imagem", name: "imagem", widget: "image" }
          - label: "Pizzas Doces"
            name: "doces"
            widget: list
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Ingredientes", name: "ingredientes", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Imagem", name: "imagem", widget: "image" }
          - label: "Bebidas"
            name: "bebidas"
            widget: list
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }